### ISSUE TITLE
Add link to github repo (for reporting bugs) on details page in Android app store

### ISSUE THREAD

**Issue by dizzib** [unquenchedservant/Unquenched-Bible#29]
I had no idea this was in github until, with joy, I discovered it in the app much later :)

Thanks!

**Comment by unquenchedservant** [comment]
I'm going to leave it only in the app, for right now, although I will try to make it more obvious (i believe right now the only thing linking to the github is the changelog, and that's largely because the website I was using to host the changelog I shut down a while back ) 

99.9% of the userbase for the app doesn't know github, and it wouldn't interest them.
