### ISSUE TITLE
Reading lists reset backwards 7 days, after update to 2.0.6

### ISSUE THREAD

**Issue by dizzib** [unquenchedservant/Unquenched-Bible#76]
After logging issue number #75 on Feb 11 I took a reading break. 8 days later on Feb 19, I updated from 2.0.3 to 2.0.6.

All reading lists have gone backwards seven days.

![Screenshot_20210219-094548](https://user-images.githubusercontent.com/1223150/108491070-5961a180-729b-11eb-98aa-cafe999893f0.png)

For example, the Gospels list has reverted from Matthew 17 to Matthew 10 (please compare this screenshot with #75), Acts 16 to Acts 9, etc.

Might this be an issue with cloud syncing?

Thanks and God bless. :)

**Comment by unquenchedservant** [comment]
It is entirely possible it's an issue with cloud syncing. I need to look at how I do that and see if I can do it better. Has it happened since?

**Comment by dizzib** [comment]
It has not happened again, but I have changed the way I use this app...

1. I have not updated the app and remain on v2.0.6
2. To avoid cloud sync issues, I have uninstalled the app off my other 2 devices and now run it only on one device.
3. To avoid list resets and reversals, I only use it when connected to the internet and not offline.

Since doing these three things it seems to be working as expected. Thanks! 😊

**Comment by unquenchedservant** [comment]
Yea, in the next few updates, i'll be changing how the cloud storage functions, as well as changing the database provider (from Firestore to MongoDB Realms). Hopefully this should fix any issues with multi-device syncing. This is especially important as I work on the web version. 

Also, with working on the web version (in React) i'll be changing the code base for the android app, so that I can have web/ios/android all on the same code. Just learning React has been a pain haha

**Comment by unquenchedservant** [comment]
Discovered the issue: 

It has to do with [DailyCheck.kt](https://github.com/unquenchedservant/Unquenched-Bible/blob/master/app/src/main/java/com/theunquenchedservant/granthornersbiblereadingsystem/utilities/DailyCheck.kt) 

compare with [the reset function in ListHelper.kt](https://github.com/unquenchedservant/Unquenched-Bible/blob/f4d9424498c218fe51c7f3b6142dba0aa46195d7/app/src/main/java/com/theunquenchedservant/granthornersbiblereadingsystem/utilities/ListHelpers.kt#L206) 

The latter pulls the data from Firestore, the former (that should run every night at midnight, in theory, but alarms are weird with Android) was pulling the data from the internal storage, then uploading to firestore. 

So what probably happened was that it finally ran the dailycheck on your second device, and ignored the fact that it was 7 days older than the current cloud data. 

I'll be doing an internal test to make sure the code change works otherwise, then pushing out to the beta channel the update that should fix cloud sync. Try it out for a few days/weeks and let me know. (I, unfortunately, do not use two different android devices)
